config/routes.rb
Rails.application.routes.draw do

  

resources :blog_posts
resources :comments, only: [:edit, :create, :update, :destroy]

  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :comments

	validates :title, :author, :blog_entry, presence: true

	validates :title, uniqueness: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post

	validates :author, :comment_entry, :blog_post_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  def index
  	@blog_posts = BlogPost.all
  end

  def new
  	@blog_post = BlogPost.new
  end

  def edit
  	
  end

  def show
  	@comment = Comment.new
  end

  def create
  	@blog_post = BlogPost.new(blog_post_params)

  	respond_to do |format|
  		if @blog_post.save
  			format.html {redirect_to @blog_post, notice: "Blog post was created successfully."}
  		else
  			format.html {render :new}
  		end
  	end
  end

  def update
	respond_to do |format|
		if @blog_post.update(blog_post_params)
			format.html {redirect_to @blog_post, notice: "Blog post was updated successfully"}
		else
			format.html {render :edit}
  end
end
end

def destroy
	@blog_post.destroy
	respond_to do |format|
		format.html {redirect_to blog_post_url, notice: "Your blog post was destroyed"}
end
end

private
	def blog_post_params
		params.require(:blog_post).permit(:title, :author, :blog_entry)
	end

	def set_blog_post
		@blog_post = BlogPost.find(params[:id])
		
	end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:edit, :update, :destroy]
  def edit
  end

  
    def create
  	@comment = Comment.new(comment_params)

  	respond_to do |format|
  		if @comment.save
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was created successfully."}
  		else
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "comment failed to post"}
  		end
  	end
  end

  def update
	respond_to do |format|
		if @comment.update(comment_params)
			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "comment was updated successfully"}
		else
			format.html {render :edit}
  end
end
end

def destroy
	@comment.destroy
	respond_to do |format|
		format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Your comment was destroyed"}
end
end

private
	def comment_params
		params.require(:comment).permit(:author, :comment_entry, :blog_post_id)
	end

	def set_comment
		@Comment = Comment.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
	<% if @blog_post.errors.any? %>
	<div class="error_explanation">
		<h2> <%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>

		<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end%>
		</ul>
	</div>
	<%end%>

	<div class = "formgroup">
		<%= f.text_field :title, class: "form_control", placeholder: "Enter your blog post name here..." %>
	</div>

	<div class = "formgroup">
		<%= f.text_field :author, class: "form_control", placeholder: "enter your name" %>
		
	</div>

	<div class = "formgroup">
		<%= f.text_area :blog_entry, class: "form_control", rows: "12", placeholder: "start typing away..." %>
	</div>

	<div class="actions">
		<%= f.submit "post", class: "btn btn-default" %>
	</div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<div class= "container">
	<%= render "form" %>
</div>

<%= link_to 'Back', @blog_post %>
<%= link_to 'Home', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Current Blog Posts</h1>

<div class = "row">
	<% @blog_posts.each do |blog_post| %>
	<div class="col-md-6">
		<div class="panel-panel-default">
			<div class = "panel-heading">
				<%= blog_post.title%>
			</div>
			<div class = "panel-body">
				by <%= blog_post.author %><br /> 
				<p><%=blog_post.blog_entry%></p>
			</div>
			<div class = "panel-footer">
				<%= link_to 'show', blog_post, class: "btn btn-primary" %>
				<%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
				<%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
			</div>
		</div>
	</div>
	<% end %>
</div>

<br />

<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>Create a new blog post</h1>

<div class="container">
	<%= render "form" %>
	</div>

<%= link_to "Back", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
	<div class = 'panel-heading'>
		<%= @blog_post.title %>
	</div>
	<div class= "panel-body">
		<h1><%= @blog_post.author %></h1>
		<p><%= @blog_post.blog_entry %></p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		comments
	</div>
	<div class="panel-body">
		<%= render @comment %>
	</div>
</div>

<div class="panel panel-success">
	make a comment
</div>
<div class="panel-body">
	<%= render 'comments/form' %>
</div>

<div>
	<%link_to "Edit", edit_blog_post_path(@blog_post) %>
	<%= link_to 'Back', blog_posts_path%>
</div>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>
		<h4><%= comment.author %></h4>
		<p><%= comment.comment_entry %></p>	
<%end%>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
	<% if @comment.errors.any? %>
	<div class="error_explanation">
		<h2> <%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

		<ul>
			<% @comment.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end%>
		</ul>
	</div>
	<%end%>

<div class="form-group">
	<%= f.text_field :author, class: "form-control", placeholder: "your name" %>
</div>

<div class="form-group">
	<%= f.text_area :comment_entry, class: "form-control", rows: "3", placeholder: "Enter comment here.."%>
	
</div>

<div class="form-group hidden">
<%= f.number_field :blog_post_id, value: @blog_post.id %>
</div>
<div class="actions"> 
 <%= f.submit "Comment", class: "btn btn-default" %>
</div>
<%end%>

app/views/comments/edit.html.erb
<h1>Editing Comment Post</h1>

<div class= "container">
	<%= render "form" %>
</div>

<%= link_to 'Back', comments %>
<%= link_to 'Home', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustBuildIT</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>